### ISSUE TITLE
System.ApplicationException in output window

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#59]
I was working a .net MAUI project, got an error where VS told me to reload the project and after the reload I got this exception in output window:

```
IDE::EXCEPTION: 10.46.41.511118:   EventProjectExit :: BlackbirdSql.Sys\AbstrusePackageController.cs :: 787
	[System.ApplicationException] Attempt to exit project event when not in a project event. _EventProjectCardinal: 0 
TRACE:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at BlackbirdSql.Diag.Dug(Exception ex, String message, String memberName, String sourceFilePath, Int32 sourceLineNumber, Boolean expected) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\Root\Diag.cs:line 326
   at BlackbirdSql.Sys.AbstrusePackageController.EventProjectExit() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\AbstrusePackageController.cs:line 788
   at BlackbirdSql.Sys.AbstrusePackageController.<>c__DisplayClass238_0.<<OnAfterOpenProject>b__1>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.CommonIDE.Solutions.Project.ReloadProject(Boolean fSuppressUpgradeWizardUI, Boolean fClearReloadState)
   at Microsoft.VisualStudio.CommonIDE.Solutions.Solution.ReloadProjectInternal(Project& pProject, Boolean fSuppressUpgradeWizardUI)
   at Microsoft.VisualStudio.CommonIDE.Solutions.Project.UnloadReloadProject(SolutionItemsProject pParentFolder, UInt32 itemidSubProject)
   at Microsoft.VisualStudio.CommonIDE.Solutions.Solution.Microsoft.VisualStudio.Shell.Interop.IVsPersistHierarchyItem2.ReloadItem(UInt32 itemid, UInt32 dwReserved)
   at Microsoft.VisualStudio.ProjectSystem.VS.VsHierarchyExtensions.ReloadProjectInSolution(IVsHierarchy hierarchy)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VsProjectFaultHostHandler.ReloadFaultedProjects()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.VsInfoBarService.InfoBarEntry.OnActionItemClicked(IVsInfoBarUIElement element, IVsInfoBarActionItem actionItem)
   at Microsoft.Internal.VisualStudio.PlatformUI.CookieTable`2.ForEach(CookieTableCallback`2 callback, Boolean skipRemoved)
   at Microsoft.VisualStudio.Platform.WindowManagement.InfoBar.InfoBarViewModel.NotifyActionItemClicked(IVsInfoBarActionItem action)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by BlackbirdSQL** [comment]
This exception will have no effect, but the event entry check `EventProjectEnter()` should have prevented entry in the first place. The condition syntax to prevent entry was incomplete.
This is an early load of the project by the IDE before the solution has signaled it is loading. Early loaded projects are often in an incomplete state so they are only checked on the solution load event.
The purpose of the routine is to ensure EF models don't fail when you have different versions of Entity Framework assemblies in different projects within the same solution.
The fix will be in the next release.

**Comment by BlackbirdSQL** [comment]
Release 13.1.0.1 is available for download. This issue has been resolved in this release.
